version: "3.8"

services:
  postgres:
    image: lalalala0/ppo_bmstu-postgres-db:latest  # Используем образ из Docker Hub
    environment:
      POSTGRES_USER: testuser
      POSTGRES_DB: testDB
      POSTGRES_PASSWORD: testpassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    networks:
      - app-network

  go-server:
    image: lalalala0/ppo_bmstu-go-server:latest  # Используем образ из Docker Hub
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    networks:
      - app-network

  react-ui:
    image: lalalala0/ppo_bmstu-react-ui:latest  # Используем образ из Docker Hub
    ports:
      - "3001:80"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://go-server:8081/api

networks:
  app-network:
    driver: bridge
