version: "3.8"

services:
  postgres-db:
    build: ./db  # Указываем путь к Dockerfile
    environment:
      POSTGRES_USER: testuser
      POSTGRES_DB: testDB
      POSTGRES_PASSWORD: testpassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    networks:
      - app-network

  go-server:
    build:
      context: .
      dockerfile: DockerfileGO  # Указываем конкретный Dockerfile для Go-сервера
    depends_on:
      - postgres-db
    ports:
      - "8081:8081"
    networks:
      - app-network

  react-ui:
    build:
      context: ./react-app
      dockerfile: DockerfileReact
    ports:
      - "3001:80"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://nginx:80/api

#  react-ui-test:
#    build:
#      context: ./react-app
#      dockerfile: DockerfileReactTests
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
