version: "3.8"

services:
  postgres:
    image: lalalala0/ppo_bmstu-postgres-db:latest  # Используем кастомный образ PostgreSQL
    environment:
      POSTGRES_USER: testuser          # Имя пользователя
      POSTGRES_DB: testDB             # Имя базы данных
      POSTGRES_PASSWORD: testpassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"                   # Порт
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Монтируем файл init.sql
      - ./db/data/:/docker-entrypoint-initdb.d/data/        # Директория с CSV-файлами
      - ./db/load_data.sql:/docker-entrypoint-initdb.d/load_data.sql  # Скрипт загрузки данных
    networks:
      - app-network

  go-server:
    image: lalalala0/ppo_bmstu-go-server:latest  # Используем кастомный образ
    build:
      context: .
      dockerfile: DockerfileGO  # Указываем конкретный Dockerfile для Go-сервера
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    networks:
      - app-network

  react-ui:
    image: lalalala0/ppo_bmstu-react-ui:latest  # Используем кастомный образ
    build:
      context: ./react-app
      dockerfile: DockerfileReact
    ports:
      - "3001:80"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://nginx:80/api

networks:
  app-network:
    driver: bridge
