receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          static_configs:
            - targets: ['localhost:8888']  # Порт, на котором будет работать OpenTelemetry

exporters:
  prometheus:
    endpoint: "0.0.0.0:8888"  # Порт для экспорта метрик в Prometheus

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheus]
