name: Go CI

on:
  push:
    branches:
      - main  # или другая ветка, которую вы используете
  pull_request:
    branches:
      - main  # или другая ветка, которую вы используете

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v2

    - name: Установка Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.4'  # Укажите версию Go, которую вы хотите использовать

    - name: Установка зависимостей
      run: go mod tidy

  
      - name: Run unit tests
        run: make ci-unit

      - name: Run integration tests
        run: make ci-integration -i

      - name: Run E2E tests
        run: make ci-e2e -i

      - name: Processing report data
        run: make ci-concat-reports -i
        if: always()
        continue-on-error: true

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: main
          path: main

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: main
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: allure-history
      

    - name: Кэширование модулей Go
      uses: actions/cache@v2
      with:
        path: /tmp/gopath/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/*.go') }}
        restore-keys: |
          ${{ runner.os }}-go-
