name: Go CI

on:
  push:
    branches:
      - main  # или другая ветка, которую вы используете
  pull_request:
    branches:
      - main  # или другая ветка, которую вы используете

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v2

      - name: Установка Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.4'  # Укажите версию Go, которую вы хотите использовать

      - name: Установка gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Установка зависимостей
        run: go mod tidy

      - name: Создание директории для Allure результатов
        run: mkdir -p ./tests/allure-results

      - name: Запуск unit тестов репозиториев
        run: gotestsum --format=standard-quiet --junitfile="./tests/allure-results/unit_tests_repo.xml" -- ./tests/unit_tests/test_repository/...

      - name: Запуск unit тестов сервисов
        run: gotestsum --format=standard-quiet --junitfile="./tests/allure-results/unit_tests_service.xml" -- ./tests/unit_tests/test_service/...

      - name: Запуск integration тестов репозиториев
        run: gotestsum --format=standard-quiet --junitfile="./tests/allure-results/integration_tests_repo.xml" -- ./tests/integration_tests/test_repository/...

      - name: Запуск integration тестов сервисов
        run: gotestsum --format=standard-quiet --junitfile="./tests/allure-results/integrationt_tests_service.xml" -- ./tests/integration_tests/test_service/...

      - name: Запуск e2e тестов
        run: gotestsum --format=standard-quiet --junitfile="./tests/allure-results/integrationt_tests_e2e.xml" -- ./tests/integration_tests/test_e2e/...

      # Установка Allure для генерации отчетов
      - name: Установка Allure
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g allure-commandline --save-dev

      - name: Генерация Allure отчета
        run: allure generate ./tests/allure-results --clean -o ./allure-report

      # Публикация отчета в GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
