name: Go CI

on:
  push:
    branches:
      - main  # или другая ветка, которую вы используете
  pull_request:
    branches:
      - main  # или другая ветка, которую вы используете

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v2

      - name: Установка Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.4'  # Укажите версию Go, которую вы хотите использовать

      - name: Установка зависимостей
        run: go mod tidy

      - name: Запуск unit тестов репозиториев
        run: go test -v ./tests/unit_tests/test_repository -json > ./tests/allure-results/test_repository.json

      - name: Запуск unit тестов сервисов
        run: go test -v ./tests/unit_tests/test_service -json > ./tests/allure-results/test_service.json

#      - name: Запуск integration тестов репозиториев
#        run: go test -v ./tests/integration_tests/test_repository -json > ./tests/allure-results/integration_test_repository.json
#
#      - name: Запуск integration тестов сервисов
#        run: go test -v ./tests/integration_tests/service_repository -json > ./tests/allure-results/integration_service_repository.json

      - name: Установка Allure
        run: |
          sudo apt-get install -y allure


      - name: Генерация отчета Allure
        run: |
          allure generate ./tests/allure-results --clean -o ./tests/allure-report

      - name: Загрузка истории отчетов тестирования
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: main
          path: main

      - name: Создание отчета тестирования
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: main
          allure_history: allure-history
          allure_results: allure-results

      - name: Публикация отчета тестирования
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: allure-history

      - name: Кэширование модулей Go
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-go-
