name: Go CI

on:
  push:
    branches:
      - main  # или другая ветка, которую вы используете
  pull_request:
    branches:
      - main  # или другая ветка, которую вы используете

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v2

      - name: Установка Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release \
            software-properties-common
          
          echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose

      - name: Установка Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.4'  # Укажите версию Go, которую вы хотите использовать

      - name: Установка зависимостей
        run: go mod tidy

      - name: Установка gotestsum
        run: go install gotest.tools/gotestsum@latest

      # Сборка Docker образа
      - name: Сборка Docker образа
        run:  docker-compose -f docker-composeWeb.yml build --no-cache

      - name: Запуск контейнеров с сервером и UI
        run: docker-compose -f docker-composeWeb.yml up -d

      - name: Запуск unit тестов (репозитории и сервисы)
        run: gotestsum --format=standard-quiet --junitfile="./tests/allure-results/unit_tests.xml" -- -parallel 5 ./tests/unit_tests/test_repository/... ./tests/unit_tests/test_service/...

      - name: Запуск integration тестов репозиториев
        run: gotestsum --format=standard-quiet --junitfile="./tests/allure-results/integration_tests_repo.xml" -- -parallel 1 ./tests/integration_tests/test_repository/...

      - name: Запуск integration тестов сервисов
        run: gotestsum --format=standard-quiet --junitfile="./tests/allure-results/integrationt_tests_service.xml" -- -parallel 1 ./tests/integration_tests/test_service/...

      - name: Запуск e2e теста + захват трафика
        run: gotestsum --format=standard-quiet --junitfile="./tests/allure-results/integrationt_tests_e2e.xml" -- -parallel 6 -count 19 ./tests/integration_tests/test_e2e/...
